-- SUPERSEDED MIGRATION
-- The profiles table, auth.users mirror trigger, and production profile RLS
-- policies are now part of the canonical setup flow.
--
-- Canonical order:
--   1. frontend/sql/database_schema.sql
--   2. frontend/sql/secure_rls_migration.sql
--
-- If you already ran this legacy script, re-run secure_rls_migration.sql to
-- remove public profile policies and apply the production-safe policy set.
SELECT 'add_profiles_table.sql is superseded; run secure_rls_migration.sql instead.' AS notice;
