-- SUPERSEDED MIGRATION
-- This legacy script created public read policies for admin statistics.
-- Admin stats now use authenticated server-side admin API access, so public
-- count policies are intentionally not part of the production RLS model.
--
-- Canonical order:
--   1. frontend/sql/database_schema.sql
--   2. frontend/sql/secure_rls_migration.sql
--
-- If you already ran this legacy script, re-run secure_rls_migration.sql to
-- drop the public count policies.
SELECT 'enable_admin_stats.sql is superseded; run secure_rls_migration.sql instead.' AS notice;
